//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by dragon.rc
//
#define IDCANCEL3                       4
#define IDD_DRAGON_DIALOG               102
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDS_HELLO                       106
#define IDI_DRAGON                      107
#define IDI_SMALL                       108
#define ID_EDITBOX_MESSAGE              110
#define ID_MESSAGE_BOX1                 111
#define ID_MESSAGE_BOX2                 112
#define IDR_MAINFRAME                   128
#define IDI_ICON1                       133
#define IDD_DIALOG_INPUT_ITEM           139
#define IDD_DIALOG1                     141
#define IDD_ITEM_OBJECT_CONTROL         145
#define IDD_VIEW_MAPOBJECT_INFO1        146
#define IDC_CURSOR1                     155
#define IDD_DIALOG2                     156
#define IDC_CURSOR2                     158
#define IDD_DIALOG3                     212
#define IDD_CHECK_EFFECT                212
#define IDD_BASIC_INFO                  213
#define IDD_WHERE_IS_HE                 214
#define IDI_ICON2                       220
#define IDB_BITMAP2                     224
#define IDC_CURSOR3                     226
#define IDR_SECURITY1                   241
#define IDD_DIALOG4                     252
#define IDR_ACCELERATOR1                263
#define IDC_BRUSH2                      1002
#define IDC_EDIT1_LEVEL                 1003
#define IDC_RADIO6                      1003
#define IDC_BRUSH3                      1003
#define IDC_EDIT2                       1004
#define IDC_RADIO7                      1004
#define EDT_MAP_NAME                    1004
#define EDT_POSY                        1004
#define IDC_RADIO8                      1005
#define IDC_RADIO4                      1006
#define IDC_SHADOW_NO                   1006
#define IDC_RADIO9                      1008
#define IDC_RADIO_ANI1                  1008
#define IDC_EDIT3                       1009
#define IDC_RADIO_ANI2                  1009
#define IDC_RADIO_ANI3                  1010
#define IDC_RADIO_ANI4                  1011
#define IDC_RADIO_ANI5                  1012
#define IDC_RADIO5                      1013
#define IDC_RADIO10                     1014
#define IDC_RADIO11                     1015
#define IDC_RADIO12                     1016
#define IDC_RADIO13                     1017
#define IDC_RADIO14                     1018
#define IDC_CHECK_DEBUGINFO             1020
#define IDC_CHECK_WEATHER_NIGHT         1023
#define IDC_ENTER_LOGINIP               1026
#define IDC_EDIT_ANITYPE                1027
#define IDC_WAIT2                       1027
#define IDC_EDIT6                       1027
#define IDC_START3                      1028
#define IDC_EDIT13                      1028
#define IDC_WAIT3                       1029
#define IDC_EDIT7                       1038
#define IDC_EDIT8                       1039
#define IDC_EDIT9                       1040
#define IDC_EDIT10                      1041
#define IDC_EDIT11                      1042
#define IDC_EDIT12                      1043
#define IDC_DONTBOX_D1                  1044
#define IDC_DONTBOX_L1                  1045
#define IDC_DONTBOX_R1                  1046
#define IDC_DONTBOX_D2                  1047
#define IDC_DONTBOX_L2                  1048
#define IDC_DONTBOX_R2                  1049
#define IDC_DONTBOX_D3                  1050
#define IDC_DONTBOX_L3                  1051
#define IDC_DONTBOX_R3                  1052
#define IDC_EDIT_CLOTH1                 1053
#define IDC_DONTBOX_D4                  1053
#define IDC_EDIT_CLOTH2                 1054
#define IDC_DONTBOX_L4                  1054
#define IDC_EDIT_CLOTH3                 1055
#define IDC_DONTBOX_R4                  1055
#define IDC_EDIT_LEVEL                  1059
#define IDC_EDIT_EXP                    1060
#define IDC_EDIT_HP                     1061
#define IDC_EDIT_MANA                   1062
#define IDC_LOGINIP                     1067
#define IDC_RADIO_ANI0                  1070
#define IDC_EDIT_ANITYPE_               1071
#define IDC_EDIT_OUT_                   1072
#define IDC_EDIT_SPRITE_                1073
#define IDC_RADIO_ITEM_YES2             1115
#define IDC_RADIO_ITEM_NO2              1116
#define IDC_RADIO_ITEM_YES3             1117
#define IDC_RADIO_ITEM_NO3              1118
#define IDC_ITEM_CHAIR                  1124
#define IDC_ITEM_TABLE                  1125
#define IDC_ITEM_DOOR                   1126
#define IDC_ITEM_BOX                    1127
#define IDC_ITEM_NORMAL                 1128
#define IDC_ITEM_SIGNBOARD              1131
#define IDC_ITEM_DIRECTBOARD            1133
#define IDC_ATTR_OFFSET_YES             1149
#define IDC_ATTR_OFFSET_NO              1150
#define IDC_BRUSH1                      1151
#define IDC_SHADOW_YES                  1153
#define IDC_DONTBOX_U1                  1214
#define IDC_DONTBOX_U2                  1215
#define IDC_DELETE_TYPE                 1215
#define IDC_DONTBOX_U3                  1216
#define IDC_DELETE_UP                   1216
#define IDC_DONTBOX_U4                  1217
#define IDC_DELETE_DOWN                 1217
#define IDC_DELETE_BUTTON               1218
#define IDC_OBS_3TYPE                   1234
#define IDC_EDIT_CHARACTER_NAME         1234
#define IDC_EDIT_MAP_NAME               1235
#define IDC_EDIT_MAP_FILE               1236
#define IDC_BUTTON_GOTO_HIM             1239
#define IDC_TAB1                        1240
#define IDC_COMBO1                      1241
#define IDC_LIST_TITLE                  1248
#define IDC_LIST1                       1260
#define IDC_START1                      1261
#define IDC_WAIT1                       1262
#define IDC_START2                      1263
#define EDT_NAME                        1270
#define BTN_ADD_USER                    1271
#define EDT_SPRNO                       1279
#define EDT_POSX                        1286
#define IDC_DROPS                       1296
#define IDC_RICHEDIT22                  1328
#define ID_UNBAN2                       1332
#define IDC_ISRARE2                     1347
#define CBO_RARE5                       1348
#define CBO_ITEMGEN_NAME2               1349
#define ID_EVENT_SCRIPT_SAVE            32773
#define ID_VIEW_NIGHT                   32780
#define ID_VIEW_NIGHT10                 32785
#define ID_VIEW_NIGHT20                 32786
#define ID_HERO_POSITION_SETTING        32791
#define ID_MENUITEM32803                32803
#define ID_PATHFIND_1                   32820
#define ID_PATHFIND_2                   32821
#define ID_PATHFIND_3                   32822
#define ID_PATHFIND_4                   32823
#define ID_PATHFIND_5                   32824
#define ID_PATHFIND_0                   32825
#define ID_TRIP_AROUND_ON               32843
#define ID_TRIP_AROUND_OFF              32844
#define ID_MESSAGE                      32848
#define ID_EVENT_LMSJOINTEAM            32891
#define ID_EVENT_LMSSTART               32892
#define ID_EVENT_DOUBLEEXP              32896
#define ID_EVENT_ENABLE                 32898
#define ID_CHECK_ADDSELFINQUEST         32900
#define ID_GM1_BANTOOL                  32903
#define ID_GM1_ENABLE                   32904
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        264
#define _APS_NEXT_COMMAND_VALUE         32907
#define _APS_NEXT_CONTROL_VALUE         1350
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
